# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/display_clock.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/clock_operation.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/alarm_function.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/slowClock_5k.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/slowClock_50k.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/slowClock_30k.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/slowClock_15k.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/pitch_up.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/pitch_down.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/alarm_clock.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/slowClock_1s.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/slowClock_50m.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/alarm_sound.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/mic_delay.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/clock_g.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/clock_a.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/clock_f.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/clock_e.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/clock_b.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/clock_d.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/clock_c.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/SPI.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/slowClock_20k.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/slowClock_40k.v}
  {C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/new/AUDIO_FX_TOP.v}
}
read_vhdl -library xil_defaultlib {{C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/sources_1/imports/audio_effects.srcs/DA2CompRef.vhd}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/constrs_1/imports/Learn/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Xian Hao/Desktop/audio_effects/audio_effects.srcs/constrs_1/imports/Learn/Basys3_Master.xdc}}]


synth_design -top AUDIO_FX_TOP -part xc7a35tcpg236-1


write_checkpoint -force -noxdef AUDIO_FX_TOP.dcp

catch { report_utilization -file AUDIO_FX_TOP_utilization_synth.rpt -pb AUDIO_FX_TOP_utilization_synth.pb }
