`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// AY1718 Sem 1 EE2020 Project
// Project Name: Audio Effects
// Module Name: AUDIO_FX_TOP
// Team No.: 
// Student Names: 
// Matric No.:
// Description: 
// 
// Work Distribution:
//////////////////////////////////////////////////////////////////////////////////

module AUDIO_FX_TOP(
    input CLK,              // 100MHz FPGA clock
    input SPECIAL_FEATURE,  // Toggles special feature
    
    input [14:0] sw,
    input btnU, btnD,
    
/*    input SWITCH_C, SWITCH_D, SWITCH_E, SWITCH_F, SWITCH_G, SWITCH_A, SWITCH_B,
    input OCTAVE_HIGHER,
    input SEMITONE_UP,
    input SEMITONE_DOWN,
    input SWITCH_MIC,     // Activates Task 1
    input SWITCH_DELAY,   // Activates Task A
 */   
    input  J_MIC3_Pin3,   // PmodMIC3 audio input data (serial)
    output J_MIC3_Pin1,   // PmodMIC3 chip select, 20kHz sampling clock
    output J_MIC3_Pin4,   // PmodMIC3 serial clock (generated by module SPI.v)
     
    output J_DA2_Pin1,    // PmodDA2 sampling clock (generated by module DA2RefComp.vhd)
    output J_DA2_Pin2,    // PmodDA2 Data_A, 12-bit speaker output (generated by module DA2RefComp.vhd)
    output J_DA2_Pin3,    // PmodDA2 Data_B, not used (generated by module DA2RefComp.vhd)
    output J_DA2_Pin4     // PmodDA2 serial clock, 50MHz clock
    );

    //////////////////////////////////////////////////////////////////////////////////
    // Instantiate Multiplexer
    reg SWITCH_C, SWITCH_D, SWITCH_E, SWITCH_F, SWITCH_G, SWITCH_A, SWITCH_B, OCTAVE_HIGHER, SEMITONE_UP, SEMITONE_DOWN, SWITCH_MIC, SWITCH_DELAY;
    
    always @ (SPECIAL_FEATURE) begin
        if (SPECIAL_FEATURE == 0) begin
            SWITCH_MIC = sw[14];
            SWITCH_DELAY = sw[13];
            
            SWITCH_C = sw[0];
            SWITCH_D = sw[1];
            SWITCH_E = sw[2];
            SWITCH_F = sw[3];
            SWITCH_G = sw[4];
            SWITCH_A = sw[5];
            SWITCH_B = sw[6];
            
            OCTAVE_HIGHER = sw[7];
            SEMITONE_UP = btnU;
            SEMITONE_DOWN = btnD;
        end
    end
            

    //////////////////////////////////////////////////////////////////////////////////
    // Clock Divider Module: Generate necessary clocks from 100MHz FPGA CLK
    // Please create the clock divider module and instantiate it here.
      wire clk_20k, clk_50M;
      
      slowClock_20k clock_unit1 (CLK, clk_20k);
      slowClock_50m clock_unit2 (CLK, clk_50M);
      
     //////////////////////////////////////////////////////////////////////////////////
     //SPI Module: Converting serial data into a 12-bit parallel register
     //Do not change the codes in this area
      wire [11:0]MIC_in;
      SPI u1 (CLK, clk_20k, J_MIC3_Pin3, J_MIC3_Pin1, J_MIC3_Pin4, MIC_in);
   
    /////////////////////////////////////////////////////////////////////////////////////
    // Real-time Audio Effect Features
    // Please create modules to implement different features and instantiate them here   
      wire [11:0] speaker_out, c, d, e, f, g, a, b, data_out;
      
      // Piano
      clock_c note_c (CLK, OCTAVE_HIGHER, SEMITONE_UP, SEMITONE_DOWN, c);
      clock_d note_d (CLK, OCTAVE_HIGHER, SEMITONE_UP, SEMITONE_DOWN, d);
      clock_e note_e (CLK, OCTAVE_HIGHER, SEMITONE_UP, SEMITONE_DOWN, e);
      clock_f note_f (CLK, OCTAVE_HIGHER, SEMITONE_UP, SEMITONE_DOWN, f);
      clock_g note_g (CLK, OCTAVE_HIGHER, SEMITONE_UP, SEMITONE_DOWN, g);
      clock_a note_a (CLK, OCTAVE_HIGHER, SEMITONE_UP, SEMITONE_DOWN, a);
      clock_b note_b (CLK, OCTAVE_HIGHER, SEMITONE_UP, SEMITONE_DOWN, b);      
      
      // Delay
      mic_delay delay1 (clk_20k, clk_20k, MIC_in, data_out);
      
      // speaker_out multiplexer
      assign speaker_out = (SWITCH_C == 1) ? c : (SWITCH_D == 1) ? d : (SWITCH_E == 1) ? e : (SWITCH_F == 1) ? f : (SWITCH_G == 1) ? g : (SWITCH_A == 1) ? a : (SWITCH_B == 1) ? b : (SWITCH_MIC == 1) ? MIC_in : (SWITCH_DELAY == 1) ? data_out : 0;
    /////////////////////////////////////////////////////////////////////////////////////
    //DAC Module: Digital-to-Analog Conversion
    //Do not change the codes in this area        
      DA2RefComp u2(clk_50M, clk_20k, speaker_out, ,1'b0, J_DA2_Pin2, J_DA2_Pin3, J_DA2_Pin4, J_DA2_Pin1,);
        
  //////////////////////////////////////////////////////////////////////////////////

endmodule
