# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/MyWork/alarm_clock/alarm_clock.cache/wt [current_project]
set_property parent.project_path D:/MyWork/alarm_clock/alarm_clock.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib D:/MyWork/alarm_clock/alarm_clock.srcs/sources_1/new/alarm_clock.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/MyWork/alarm_clock/alarm_clock.srcs/constrs_1/imports/Learn/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/MyWork/alarm_clock/alarm_clock.srcs/constrs_1/imports/Learn/Basys3_Master.xdc]


synth_design -top alarm_clock -part xc7a35tcpg236-1


write_checkpoint -force -noxdef alarm_clock.dcp

catch { report_utilization -file alarm_clock_utilization_synth.rpt -pb alarm_clock_utilization_synth.pb }
